@startuml before
allow_mixing

skinparam sequence {
	ArrowColor DarkRed
}

frame Profiles as PRO #LightGrey {
  
  package PRO_PI as "PSIGEL" #SlateGrey {

    package PRO_PI_Session as "Sessions" #LightGrey {
      object PRO_RDP_Session01 {
        id = 529
      }
    }

    package PRO_PI_Accessories as "Accessories" #LightGrey {
      object PRO_Terminal_LocalTerminal {
        id = 532
      }
    }

    package PRO_PI_UserInterface as "User Interface" #Yellow {
      object PRO_LNG_DE #Yellow {
        id = 535
      }
    }

    package PRO_PI_Network as "Network" #LightGrey {
      object PRO_NW_LAN {
        id = 537
      }
      object PRO_NW_WLAN {
        id = 538
      }
    }

    package PRO_PI_Devices as "Devices" #Green {
    }

    package PRO_PI_Security as "Security" #LightGrey {
      object PRO_PW_Root {
        id = 540
      }
    }

    package PRO_PI_System as "System" #Red {
      object PRO_TZ_CET #Red {
        id = 542
      }
    }

  }

  PRO_RDP_Session01 -down. PRO_Terminal_LocalTerminal
  PRO_Terminal_LocalTerminal -down. PRO_LNG_DE
  PRO_LNG_DE -down. PRO_NW_LAN
  PRO_NW_LAN -down. PRO_NW_WLAN
  PRO_NW_WLAN -down. PRO_PW_Root
  PRO_PW_Root -down. PRO_TZ_CET
  PRO_PI_System -down. PRO_PI_Devices

}

frame Devices as DEV #LightGrey {

  package DEV_PI as "PSIGEL" #SlateGrey {

    package DEV_PI_BR as "Bremen" #LightGrey {

      package DEV_PI_BR_HR as "HR" #SlateGrey {

        object 0A0000000001 {
          id = 505
          name = BR-HR-001
          mac = 0A0000000001
        }

        object 0A0000000002 {
          id = 507
          name = BR-HR-002
          mac = 0A0000000002
        }

      }

      package DEV_PI_BR_MKT as "Marketing" #SlateGrey {

        object 0A0000000003 {
          id = 577
          name = BR-MKT-003
          mac = 0A0000000003
        }

        object 0A0000000004 {
          id = 576
          name = BR-MKT-004
          mac = 0A0000000004
        }

      }

      package DEV_PI_BR_DEV as "Development" #Yellow {

        object 0A0000000010 #Yellow {
          id = 
          name = DEV_PI_BR_DEV_001
          mac = 0A0000000010
        }

      }

    }

    package DEV_PI_A as "Augsburg" #LightGrey {

      package DEV_PI_A_DEV as "Development" #SlateGrey {

        object 0A0000000005 {
          id = 512
          name = A-DEV-005
          mac = 0A0000000005
        }

        object 0A0000000006 {
          id = 513
          name = A-DEV-006
          mac = 0A0000000006
        }

        object 0A0000000009 #Yellow {
          id = 518
          name = A-DEV-009
          mac = 0A0000000009
        }

      }

      package DEV_PI_A_QA as "QandA" #Green {

        object 0A0000000007 #Green {
          id = 
          name = A-QA-007
          mac = 0A0000000007
        }

        object 0A0000000008 #Green {
          id = 
          name = A-QA-008
          mac = 0A0000000008
        }

      }

    }

    package DEV_PI_L as "Leipzig" #LightGrey {

      package DEV_PI_L_DIS as "Distribution" #Red {

        object 0A0000000011 #Red {
          id = 521
          name = L-DIS-011
          mac = 0A0000000011
        }

        object 0A0000000012 #Red {
          id = 522
          name = L-DIS-012
          mac = 0A0000000012
        }

      }

    }
  }

  0A0000000001 -down. 0A0000000002
  0A0000000002 -down. 0A0000000003
  0A0000000003 -down. 0A0000000004
  0A0000000004 -down. 0A0000000010
  0A0000000010 -down. 0A0000000005
  0A0000000005 -down. 0A0000000006
  0A0000000006 -down. 0A0000000009
  0A0000000009 -down. 0A0000000007
  0A0000000007 -down. 0A0000000008
  0A0000000008 -down. 0A0000000011
  0A0000000011 -down. 0A0000000012

}

frame Functions as FUN #LightGrey {

  package FUN_DEV as "Device" #SlateGrey {

    node [NewUMSDevice]
    node [RemoveUMSDevice]
    node [MoveUMSDevice]
    node [UpdateUMSDevice]
    node [GetUMSDevice]

  }

  package FUN_DEVDIR as "DeviceDir" #SlateGrey {

    node [NewUMSDeviceDirectory]
    node [RemoveUMSDeviceDirectory]
    node [MoveUMSDeviceDirectory]
    node [UpdateUMSDeviceDirectory]
    node [GetUMSDeviceDirectory]

  }

  package FUN_PRO as "Profile" #SlateGrey {

    node [RemoveUMSProfile]
    node [MoveUMSProfile]
    node [UpdateUMSProfile]
    node [GetUMSProfile]

  }

  package FUN_PRODIR as "ProfileDir" #SlateGrey {

    node [NewUMSProfileDirectory]
    node [RemoveUMSProfileDirectory]
    node [MoveUMSProfileDirectory]
    node [UpdateUMSProfileDirectory]
    node [GetUMSProfileDirectory]

  }

  package FUN_PROASS as "ProfileAss" #SlateGrey {

    node [NewUMSProfileAssignment]
    node [RemoveUMSProfileAssignment]
    node [GetUMSProfileAssignment]
    node [GetUMSDeviceAssignment]
    node [GetUMSDeviceDirectoryAssignment]

  }

  NewUMSDevice -down. RemoveUMSDevice
  RemoveUMSDevice -down. MoveUMSDevice
  MoveUMSDevice -down. UpdateUMSDevice
  UpdateUMSDevice -down. GetUMSDevice
  GetUMSDevice -down. NewUMSDeviceDirectory
  NewUMSDeviceDirectory -down. RemoveUMSDeviceDirectory
  RemoveUMSDeviceDirectory -down. MoveUMSDeviceDirectory
  MoveUMSDeviceDirectory -down. UpdateUMSDeviceDirectory
  UpdateUMSDeviceDirectory -down. GetUMSDeviceDirectory
  GetUMSDeviceDirectory -down. RemoveUMSProfile
  RemoveUMSProfile -down. MoveUMSProfile
  MoveUMSProfile -down. UpdateUMSProfile
  UpdateUMSProfile -down. GetUMSProfile
  GetUMSProfile -down. NewUMSProfileDirectory
  NewUMSProfileDirectory -down. RemoveUMSProfileDirectory
  RemoveUMSProfileDirectory -down. MoveUMSProfileDirectory
  MoveUMSProfileDirectory -down. UpdateUMSProfileDirectory
  UpdateUMSProfileDirectory -down. GetUMSProfileDirectory
  GetUMSProfileDirectory -down. NewUMSProfileAssignment
  NewUMSProfileAssignment -down. RemoveUMSProfileAssignment
  RemoveUMSProfileAssignment -down. GetUMSProfileAssignment
  GetUMSProfileAssignment -down. GetUMSDeviceAssignment
  GetUMSDeviceAssignment -down. GetUMSDeviceDirectoryAssignment

}

PRO_RDP_Session01 -right-+ DEV_PI
PRO_Terminal_LocalTerminal -right-+ DEV_PI_A_DEV
PRO_Terminal_LocalTerminal -right-+ DEV_PI_BR_DEV
PRO_LNG_DE -right-+ DEV_PI
PRO_NW_LAN -right-+ DEV_PI_BR
PRO_NW_WLAN -right-+ DEV_PI_BR_DEV
PRO_PW_Root -right-+ DEV_PI

'New
NewUMSDeviceDirectory -right-> DEV_PI_A_QA : 01 - New-UMSDeviceDirectory
NewUMSDevice -right-> 0A0000000007 : 02 - New-UMSDevice
NewUMSDevice -right-> 0A0000000008 : 03 - New-UMSDevice
NewUMSProfileDirectory -right-> PRO_PI_Devices : 04 - New-UMSProfileDirectory
PRO_NW_WLAN -right-> NewUMSProfileAssignment : 05 - NewUMSProfileAssignment tc
NewUMSProfileAssignment -right-+ 0A0000000003 : 05 - NewUMSProfileAssignment tc
PRO_NW_WLAN -right-> NewUMSProfileAssignment : 06 - NewUMSProfileAssignment tcdir
NewUMSProfileAssignment -right-+ DEV_PI_BR_HR : 06 - NewUMSProfileAssignment tcdir

'Remove
RemoveUMSDevice -right-> 0A0000000011 : 07 - Remove-UMSDevice
RemoveUMSDevice -right-> 0A0000000012 : 08 - Remove-UMSDevice
RemoveUMSDeviceDirectory -right-> DEV_PI_L_DIS : 09 - Remove-UMSDeviceDirectory
RemoveUMSProfile -right-> PRO_TZ_CET : 10 - Remove-UMSProfile
RemoveUMSProfileDirectory -right-> PRO_PI_System : 11 - Remove-UMSProfileDirectory
DEV_PI -right-> RemoveUMSProfileAssignment : 12 - Remove-UMSProfileAssignment tcdir
RemoveUMSProfileAssignment -right-> PRO_TZ_CET : 12 - Remove-UMSProfileAssignment tcdir
0A0000000001 -right-> RemoveUMSProfileAssignment : 13 - Remove-UMSProfileAssignment tc
RemoveUMSProfileAssignment -right-> PRO_PW_Root : 13 - Remove-UMSProfileAssignment tc

'Move
MoveUMSDevice -right-> 0A0000000009 : 14 - Move-UMSDevice
MoveUMSDeviceDirectory -right-> DEV_PI_A_QA: 15 - Move-UMSDeviceDirectory DEV_PI_A_QA
MoveUMSDeviceDirectory -right-> DEV_PI_BR_DEV: 15 - Move-UMSDeviceDirectory DEV_PI_L_DEV
MoveUMSProfile -right-> PRO_LNG_DE : 16 - Move-UMSProfile
MoveUMSProfileDirectory -right-> PRO_PI_UserInterface : 17 - Move-UMSProfileDirectory

'Update
UpdateUMSDeviceDirectory -right-> DEV_PI_BR_DEV : 18 - Update-UMSDeviceDirectory
UpdateUMSDevice -right-> 0A0000000010 : 19 - Update-UMSDevice
UpdateUMSDevice -right-> 0A0000000009 : 20 - Update-UMSDevice
UpdateUMSProfile -right-> PRO_LNG_DE : 21 - Update- UMSProfile PRO_NW_LNG_DE
UpdateUMSProfileDirectory -right-> PRO_PI_UserInterface : 22 - PRO_PI_Network_UserInterface

'Get
GetUMSDevice -right-> DEV : 23 - Get-UMSDevice
GetUMSDevice -right-> 0A0000000001 : 24 - Get-UMSDevice
GetUMSDeviceDirectory -right-> DEV : 25 - Get-UMSDeviceDirectory
GetUMSProfile -right-> PRO : 26 - GetUMSProfile
GetUMSProfileDirectory -right-> PRO : 27 - Get-UMSProfileDirectory
GetUMSProfileAssignment -right-> PRO_RDP_Session01 : 28 - Get-UMSProfileAssignment Device
GetUMSProfileAssignment -right-> PRO_RDP_Session01 : 29 - Get-UMSProfileAssignment Directory
GetUMSDeviceAssignment -right-> 0A0000000001 : 30 - Get-UMSDeviceAssignment
GetUMSDeviceDirectoryAssignment -right-> DEV_PI_BR : 31 - Get-UMSDeviceDirectoryAssignment

@enduml